apiVersion: designate.openstack.org/v1beta1
kind: DesignateBackendbind9
metadata:
  name: designatebackendbind9-sample
spec:
  # TODO(user): Add fields here
  secret: osp-secret
  serviceUser: designate
  customServiceConfig: |
    [DEFAULT]
    debug = true
  databaseInstance: openstack
  databaseUser: designate
  rabbitMqClusterName: rabbitmq
  designateBackendbind9:
    containerImage: quay.io/tripleowallabycentos9/openstack-designate-backend-bind9:current-tripleo
